version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      root-dependencies:
        patterns:
          - "*"
  - package-ecosystem: npm
    directory: /workers
    schedule:
      interval: weekly
    groups:
      worker-dependencies:
        patterns:
          - "*"
