version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      root-compatible:
        patterns:
          - "*"
        update-types: ["minor", "patch"]
  - package-ecosystem: npm
    directory: /workers
    schedule:
      interval: weekly
    groups:
      worker-compatible:
        patterns:
          - "*"
        update-types: ["minor", "patch"]
